// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-classes.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
var list_classes_default = defineTool({
  name: "list_classes",
  title: "List classes",
  description: "List upcoming Studio Roxx classes on the schedule, with instructor, level, capacity, and pricing. Public data \u2014 anyone signed in can browse.",
  inputSchema: {
    days_ahead: z.number().int().optional().describe("How many days ahead to fetch (default 14, max 60)."),
    level: z.string().optional().describe("Filter by class level (e.g. Beginner, Intermediate)."),
    instructor: z.string().optional().describe("Filter by instructor name (partial match).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days_ahead, level, instructor }) => {
    const sb = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const days = Math.min(Math.max(days_ahead ?? 14, 1), 60);
    const from = /* @__PURE__ */ new Date();
    from.setHours(0, 0, 0, 0);
    const to = new Date(from);
    to.setDate(to.getDate() + days);
    let q = sb.from("classes").select(
      "id, title, instructor, level, starts_at, duration_minutes, spots_total, drop_in_price, pass_price, subscription_price, description"
    ).gte("starts_at", from.toISOString()).lt("starts_at", to.toISOString()).order("starts_at");
    if (level) q = q.eq("level", level);
    if (instructor) q = q.ilike("instructor", `%${instructor}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { classes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-bookings.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.110.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sbForUser(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_bookings_default = defineTool2({
  name: "list_my_bookings",
  title: "List my bookings",
  description: "List the signed-in user's bookings, including upcoming and past classes.",
  inputSchema: {
    scope: z2.enum(["upcoming", "past", "all"]).optional().describe("Filter bookings by time (default: upcoming).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ scope }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sbForUser(ctx).from("bookings").select(
      "id, tier, price, status, created_at, classes(id, title, instructor, starts_at, duration_minutes)"
    ).eq("user_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const now = Date.now();
    const s = scope ?? "upcoming";
    const rows = (data ?? []).filter((b) => {
      const c = b.classes;
      if (!c?.starts_at) return s === "all";
      const t = new Date(c.starts_at).getTime();
      if (s === "upcoming") return t >= now && b.status === "confirmed";
      if (s === "past") return t < now;
      return true;
    });
    return {
      content: [{ type: "text", text: JSON.stringify(rows) }],
      structuredContent: { bookings: rows }
    };
  }
});

// src/lib/mcp/tools/book-class.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.110.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
function sbForUser2(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var book_class_default = defineTool3({
  name: "book_class",
  title: "Book a class",
  description: "Book a Studio Roxx class for the signed-in user using drop-in, class pass, or monthly subscription. Confirms capacity atomically. Signing the waiver is required \u2014 booking via MCP counts as accepting the studio waiver on file.",
  inputSchema: {
    class_id: z3.string().uuid().describe("The class UUID to book."),
    tier: z3.enum(["drop-in", "pass", "subscription"]).describe("Payment tier to use for this booking."),
    discount_code: z3.string().optional().describe("Optional discount code.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ class_id, tier, discount_code }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = sbForUser2(ctx);
    const { data: cls, error: cErr } = await sb.from("classes").select("drop_in_price, pass_price, subscription_price, title, starts_at").eq("id", class_id).maybeSingle();
    if (cErr || !cls) {
      return { content: [{ type: "text", text: cErr?.message ?? "Class not found" }], isError: true };
    }
    const price = tier === "drop-in" ? Number(cls.drop_in_price) : tier === "pass" ? Number(cls.pass_price) : Number(cls.subscription_price);
    const { data, error } = await sb.rpc("book_class", {
      _class_id: class_id,
      _tier: tier,
      _total_amount: price,
      _discount_code: discount_code ?? null,
      _discount_percent: 0
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [
        {
          type: "text",
          text: `Booked ${cls.title} at ${cls.starts_at} (${tier}). Booking id: ${data}`
        }
      ],
      structuredContent: { booking_id: data, class: cls, tier, price }
    };
  }
});

// src/lib/mcp/tools/cancel-booking.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.110.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^3.25.76";
function sbForUser3(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var cancel_booking_default = defineTool4({
  name: "cancel_booking",
  title: "Cancel a booking",
  description: "Cancel one of the signed-in user's existing bookings by id.",
  inputSchema: {
    booking_id: z4.string().uuid().describe("The booking UUID to cancel.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ booking_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sbForUser3(ctx).from("bookings").update({ status: "cancelled" }).eq("id", booking_id).eq("user_id", ctx.getUserId()).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Booking not found" }], isError: true };
    return {
      content: [{ type: "text", text: `Cancelled booking ${booking_id}` }],
      structuredContent: { booking: data }
    };
  }
});

// src/lib/mcp/tools/get-profile.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.110.2";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
function sbForUser4(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_profile_default = defineTool5({
  name: "get_profile",
  title: "Get my profile",
  description: "Return the signed-in user's Studio Roxx profile, including display name and waiver-signed status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sbForUser4(ctx).from("profiles").select("*").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify({ email: ctx.getUserEmail(), profile: data }) }],
      structuredContent: { email: ctx.getUserEmail(), user_id: ctx.getUserId(), profile: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wbjqsxrwfwmseugjuzqe";
var mcp_default = defineMcp({
  name: "studio-roxx-mcp",
  title: "Studio Roxx",
  version: "0.1.0",
  instructions: "Studio Roxx pole studio booking. Use list_classes to browse the schedule, book_class to reserve a spot, list_my_bookings to see your bookings, cancel_booking to release a spot, and get_profile for account info. All booking actions are scoped to the signed-in user via OAuth.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_classes_default, list_my_bookings_default, book_class_default, cancel_booking_default, get_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
